# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_REQUEST_MSGID = descriptor.EnumDescriptor(
  name='request_msgid',
  full_name='badoo.meetmaker.request_msgid',
  filename='request_msgid',
  values=[
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_ADD', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_UPDATE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_GET', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_FILTER_SET', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_DELETE', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_MARK_AS_OLD', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_COUNTERS_GET', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_PHOTO_ADD', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_PHOTO_UPDATE', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_PHOTO_DELETE', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_DEMO_ADD', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_VOTE_ADD', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_FOLDER_LIST', index=12, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SHOW_NEXT', index=13, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SHOW_MOVE_TO_BEGINNING', index=14, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_VOTE_INFO', index=15, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_FILTER_GET_MAX', index=16, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SHOW_CLEAN', index=17, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_LOCK', index=18, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SERVICE_STATS_GENERAL', index=19, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SERVICE_STATS_MEM_USAGE', index=20, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SERVICE_STATS_DEMO', index=21, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SERVICE_STATS_VOTES', index=22, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SERVICE_STATS_SHOWS', index=23, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_SUSPEND', index=24, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_USER_HIDE_CONTACT', index=25, number=26,
      options=None,
      type=None),
  ],
  options=None,
)


_RESPONSE_MSGID = descriptor.EnumDescriptor(
  name='response_msgid',
  full_name='badoo.meetmaker.response_msgid',
  filename='response_msgid',
  values=[
    descriptor.EnumValueDescriptor(
      name='RESPONSE_GENERIC', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_USER_GET', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_VOTE_ADD', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_FOLDER_LIST', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_USER_COUNTERS_GET', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_SHOW_NEXT', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_VOTE_INFO', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_USER_FILTER_GET_MAX', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_SERVICE_STATS_GENERAL', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_SERVICE_STATS_MEM_USAGE', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_SERVICE_STATS_DEMO', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_SERVICE_STATS_VOTES', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_SERVICE_STATS_SHOWS', index=12, number=13,
      options=None,
      type=None),
  ],
  options=None,
)


_ERRNO = descriptor.EnumDescriptor(
  name='errno',
  full_name='badoo.meetmaker.errno',
  filename='errno',
  values=[
    descriptor.EnumValueDescriptor(
      name='ERRNO_GENERIC', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERRNO_PHOTO_EXIST', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERRNO_USER_NOT_EXIST', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERRNO_PHOTO_NOT_EXIST', index=3, number=4,
      options=None,
      type=None),
  ],
  options=None,
)


_USER_GENDER = descriptor.EnumDescriptor(
  name='user_gender',
  full_name='badoo.meetmaker.user_gender',
  filename='user_gender',
  values=[
    descriptor.EnumValueDescriptor(
      name='GENDER_MALE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GENDER_FEMALE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GENDER_ANY', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_AROUND_TYPE = descriptor.EnumDescriptor(
  name='around_type',
  full_name='badoo.meetmaker.around_type',
  filename='around_type',
  values=[
    descriptor.EnumValueDescriptor(
      name='THIS_CITY', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AROUND_25_KM', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AROUND_50_KM', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AROUND_100_KM', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AROUND_200_KM', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FARTHER_200_KM', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AROUND_15_MI', index=6, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AROUND_30_MI', index=7, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AROUND_60_MI', index=8, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AROUND_120_MI', index=9, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FARTHER_120_MI', index=10, number=5,
      options=None,
      type=None),
  ],
  options=None,
)


_DEMO_PRIORITY = descriptor.EnumDescriptor(
  name='demo_priority',
  full_name='badoo.meetmaker.demo_priority',
  filename='demo_priority',
  values=[
    descriptor.EnumValueDescriptor(
      name='DEMO_PRIORITY_ACTIVE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEMO_PRIORITY_NEW', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEMO_PRIORITY_PAID', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEMO_PRIORITY_PASSIVE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEMO_PRIORITY_TOPRATED', index=4, number=5,
      options=None,
      type=None),
  ],
  options=None,
)


_VOTE_TYPE = descriptor.EnumDescriptor(
  name='vote_type',
  full_name='badoo.meetmaker.vote_type',
  filename='vote_type',
  values=[
    descriptor.EnumValueDescriptor(
      name='VOTE_EMPTY', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VOTE_YES', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VOTE_NO', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VOTE_MAYBE', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_FOLDER_TYPE = descriptor.EnumDescriptor(
  name='folder_type',
  full_name='badoo.meetmaker.folder_type',
  filename='folder_type',
  values=[
    descriptor.EnumValueDescriptor(
      name='FOLDER_MATCH', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FOLDER_WANT_YOU', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FOLDER_YOU_WANT', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


REQUEST_USER_ADD = 1
REQUEST_USER_UPDATE = 2
REQUEST_USER_GET = 3
REQUEST_USER_FILTER_SET = 4
REQUEST_USER_DELETE = 5
REQUEST_USER_MARK_AS_OLD = 6
REQUEST_USER_COUNTERS_GET = 7
REQUEST_PHOTO_ADD = 8
REQUEST_PHOTO_UPDATE = 9
REQUEST_PHOTO_DELETE = 10
REQUEST_DEMO_ADD = 11
REQUEST_VOTE_ADD = 12
REQUEST_FOLDER_LIST = 13
REQUEST_SHOW_NEXT = 14
REQUEST_SHOW_MOVE_TO_BEGINNING = 15
REQUEST_VOTE_INFO = 16
REQUEST_USER_FILTER_GET_MAX = 17
REQUEST_SHOW_CLEAN = 18
REQUEST_USER_LOCK = 19
REQUEST_SERVICE_STATS_GENERAL = 20
REQUEST_SERVICE_STATS_MEM_USAGE = 21
REQUEST_SERVICE_STATS_DEMO = 22
REQUEST_SERVICE_STATS_VOTES = 23
REQUEST_SERVICE_STATS_SHOWS = 24
REQUEST_USER_SUSPEND = 25
REQUEST_USER_HIDE_CONTACT = 26
RESPONSE_GENERIC = 1
RESPONSE_USER_GET = 2
RESPONSE_VOTE_ADD = 3
RESPONSE_FOLDER_LIST = 4
RESPONSE_USER_COUNTERS_GET = 5
RESPONSE_SHOW_NEXT = 6
RESPONSE_VOTE_INFO = 7
RESPONSE_USER_FILTER_GET_MAX = 8
RESPONSE_SERVICE_STATS_GENERAL = 9
RESPONSE_SERVICE_STATS_MEM_USAGE = 10
RESPONSE_SERVICE_STATS_DEMO = 11
RESPONSE_SERVICE_STATS_VOTES = 12
RESPONSE_SERVICE_STATS_SHOWS = 13
ERRNO_GENERIC = 1
ERRNO_PHOTO_EXIST = 2
ERRNO_USER_NOT_EXIST = 3
ERRNO_PHOTO_NOT_EXIST = 4
GENDER_MALE = 1
GENDER_FEMALE = 2
GENDER_ANY = 3
THIS_CITY = 0
AROUND_25_KM = 1
AROUND_50_KM = 2
AROUND_100_KM = 3
AROUND_200_KM = 4
FARTHER_200_KM = 5
AROUND_15_MI = 1
AROUND_30_MI = 2
AROUND_60_MI = 3
AROUND_120_MI = 4
FARTHER_120_MI = 5
DEMO_PRIORITY_ACTIVE = 1
DEMO_PRIORITY_NEW = 2
DEMO_PRIORITY_PAID = 3
DEMO_PRIORITY_PASSIVE = 4
DEMO_PRIORITY_TOPRATED = 5
VOTE_EMPTY = 0
VOTE_YES = 1
VOTE_NO = 2
VOTE_MAYBE = 3
FOLDER_MATCH = 1
FOLDER_WANT_YOU = 2
FOLDER_YOU_WANT = 3



_RESPONSE_GENERIC = descriptor.Descriptor(
  name='response_generic',
  full_name='badoo.meetmaker.response_generic',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error_code', full_name='badoo.meetmaker.response_generic.error_code', index=0,
      number=1, type=17, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_text', full_name='badoo.meetmaker.response_generic.error_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_USER_PHOTO = descriptor.Descriptor(
  name='user_photo',
  full_name='badoo.meetmaker.user_photo',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='photo_id', full_name='badoo.meetmaker.user_photo.photo_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='badoo.meetmaker.user_photo.width', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='badoo.meetmaker.user_photo.height', index=2,
      number=3, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='updated', full_name='badoo.meetmaker.user_photo.updated', index=3,
      number=4, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vote_yes_count', full_name='badoo.meetmaker.user_photo.vote_yes_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vote_no_count', full_name='badoo.meetmaker.user_photo.vote_no_count', index=5,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vote_maybe_count', full_name='badoo.meetmaker.user_photo.vote_maybe_count', index=6,
      number=7, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_ADD = descriptor.Descriptor(
  name='request_user_add',
  full_name='badoo.meetmaker.request_user_add',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_add.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='age', full_name='badoo.meetmaker.request_user_add.age', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='country_id', full_name='badoo.meetmaker.request_user_add.country_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='city_id', full_name='badoo.meetmaker.request_user_add.city_id', index=3,
      number=5, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gender', full_name='badoo.meetmaker.request_user_add.gender', index=4,
      number=6, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_gender', full_name='badoo.meetmaker.request_user_add.looking_gender', index=5,
      number=7, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_age_from', full_name='badoo.meetmaker.request_user_add.looking_age_from', index=6,
      number=8, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_age_to', full_name='badoo.meetmaker.request_user_add.looking_age_to', index=7,
      number=9, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_around', full_name='badoo.meetmaker.request_user_add.looking_around', index=8,
      number=11, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo', full_name='badoo.meetmaker.request_user_add.photo', index=9,
      number=10, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_UPDATE = descriptor.Descriptor(
  name='request_user_update',
  full_name='badoo.meetmaker.request_user_update',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_update.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='age', full_name='badoo.meetmaker.request_user_update.age', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gender', full_name='badoo.meetmaker.request_user_update.gender', index=2,
      number=3, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='city_id', full_name='badoo.meetmaker.request_user_update.city_id', index=3,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='country_id', full_name='badoo.meetmaker.request_user_update.country_id', index=4,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_DELETE = descriptor.Descriptor(
  name='request_user_delete',
  full_name='badoo.meetmaker.request_user_delete',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_delete.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_GET = descriptor.Descriptor(
  name='request_user_get',
  full_name='badoo.meetmaker.request_user_get',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_get.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_USER_GET = descriptor.Descriptor(
  name='response_user_get',
  full_name='badoo.meetmaker.response_user_get',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='age', full_name='badoo.meetmaker.response_user_get.age', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gender', full_name='badoo.meetmaker.response_user_get.gender', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='country_id', full_name='badoo.meetmaker.response_user_get.country_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='city_id', full_name='badoo.meetmaker.response_user_get.city_id', index=3,
      number=5, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_gender', full_name='badoo.meetmaker.response_user_get.looking_gender', index=4,
      number=7, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_age_from', full_name='badoo.meetmaker.response_user_get.looking_age_from', index=5,
      number=8, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_age_to', full_name='badoo.meetmaker.response_user_get.looking_age_to', index=6,
      number=9, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_around', full_name='badoo.meetmaker.response_user_get.looking_around', index=7,
      number=15, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photos_count', full_name='badoo.meetmaker.response_user_get.photos_count', index=8,
      number=10, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_locked', full_name='badoo.meetmaker.response_user_get.is_locked', index=9,
      number=14, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_suspended', full_name='badoo.meetmaker.response_user_get.is_suspended', index=10,
      number=16, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_PHOTO_ADD = descriptor.Descriptor(
  name='request_photo_add',
  full_name='badoo.meetmaker.request_photo_add',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_photo_add.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo', full_name='badoo.meetmaker.request_photo_add.photo', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_PHOTO_UPDATE = descriptor.Descriptor(
  name='request_photo_update',
  full_name='badoo.meetmaker.request_photo_update',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_photo_update.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo', full_name='badoo.meetmaker.request_photo_update.photo', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_PHOTO_DELETE = descriptor.Descriptor(
  name='request_photo_delete',
  full_name='badoo.meetmaker.request_photo_delete',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_photo_delete.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo_id', full_name='badoo.meetmaker.request_photo_delete.photo_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_DEMO_ADD = descriptor.Descriptor(
  name='request_demo_add',
  full_name='badoo.meetmaker.request_demo_add',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_demo_add.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='quantity', full_name='badoo.meetmaker.request_demo_add.quantity', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='priority', full_name='badoo.meetmaker.request_demo_add.priority', index=2,
      number=3, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_VOTE_ADD = descriptor.Descriptor(
  name='request_vote_add',
  full_name='badoo.meetmaker.request_vote_add',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='from_user_id', full_name='badoo.meetmaker.request_vote_add.from_user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to_user_id', full_name='badoo.meetmaker.request_vote_add.to_user_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo_id', full_name='badoo.meetmaker.request_vote_add.photo_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vote', full_name='badoo.meetmaker.request_vote_add.vote', index=3,
      number=4, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='badoo.meetmaker.request_vote_add.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_VOTE_ADD = descriptor.Descriptor(
  name='response_vote_add',
  full_name='badoo.meetmaker.response_vote_add',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='his_vote', full_name='badoo.meetmaker.response_vote_add.his_vote', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_FILTER_SET = descriptor.Descriptor(
  name='request_user_filter_set',
  full_name='badoo.meetmaker.request_user_filter_set',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_filter_set.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_gender', full_name='badoo.meetmaker.request_user_filter_set.looking_gender', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_age_from', full_name='badoo.meetmaker.request_user_filter_set.looking_age_from', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_age_to', full_name='badoo.meetmaker.request_user_filter_set.looking_age_to', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_around', full_name='badoo.meetmaker.request_user_filter_set.looking_around', index=4,
      number=5, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_MARK_AS_OLD = descriptor.Descriptor(
  name='request_user_mark_as_old',
  full_name='badoo.meetmaker.request_user_mark_as_old',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_mark_as_old.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_user_id', full_name='badoo.meetmaker.request_user_mark_as_old.target_user_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_FOLDER_LIST = descriptor.Descriptor(
  name='request_folder_list',
  full_name='badoo.meetmaker.request_folder_list',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_folder_list.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='folder', full_name='badoo.meetmaker.request_folder_list.folder', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='badoo.meetmaker.request_folder_list.offset', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='limit', full_name='badoo.meetmaker.request_folder_list.limit', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='only_new', full_name='badoo.meetmaker.request_folder_list.only_new', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='only_with_photos', full_name='badoo.meetmaker.request_folder_list.only_with_photos', index=5,
      number=6, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='only_unanswered', full_name='badoo.meetmaker.request_folder_list.only_unanswered', index=6,
      number=7, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_FOLDER_LIST_USER_DATA = descriptor.Descriptor(
  name='user_data',
  full_name='badoo.meetmaker.response_folder_list.user_data',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.response_folder_list.user_data.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_new', full_name='badoo.meetmaker.response_folder_list.user_data.is_new', index=1,
      number=2, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_paid', full_name='badoo.meetmaker.response_folder_list.user_data.is_paid', index=2,
      number=3, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='my_vote', full_name='badoo.meetmaker.response_folder_list.user_data.my_vote', index=3,
      number=4, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='his_vote', full_name='badoo.meetmaker.response_folder_list.user_data.his_vote', index=4,
      number=5, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_RESPONSE_FOLDER_LIST = descriptor.Descriptor(
  name='response_folder_list',
  full_name='badoo.meetmaker.response_folder_list',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='total', full_name='badoo.meetmaker.response_folder_list.total', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='badoo.meetmaker.response_folder_list.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_COUNTERS_GET = descriptor.Descriptor(
  name='request_user_counters_get',
  full_name='badoo.meetmaker.request_user_counters_get',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_counters_get.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_USER_COUNTERS_GET = descriptor.Descriptor(
  name='response_user_counters_get',
  full_name='badoo.meetmaker.response_user_counters_get',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='folder_mutual_new', full_name='badoo.meetmaker.response_user_counters_get.folder_mutual_new', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='folder_mutual_all', full_name='badoo.meetmaker.response_user_counters_get.folder_mutual_all', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='folder_you_want', full_name='badoo.meetmaker.response_user_counters_get.folder_you_want', index=2,
      number=3, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='folder_want_you_new', full_name='badoo.meetmaker.response_user_counters_get.folder_want_you_new', index=3,
      number=4, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='folder_want_you_all', full_name='badoo.meetmaker.response_user_counters_get.folder_want_you_all', index=4,
      number=5, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='you_will_be_shown', full_name='badoo.meetmaker.response_user_counters_get.you_will_be_shown', index=5,
      number=6, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='want_you_out_of_search', full_name='badoo.meetmaker.response_user_counters_get.want_you_out_of_search', index=6,
      number=7, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='your_votes_last_24_hours', full_name='badoo.meetmaker.response_user_counters_get.your_votes_last_24_hours', index=7,
      number=8, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
    descriptor.FieldDescriptor(
      name='votes_in_last24h', full_name='badoo.meetmaker.response_user_counters_get.votes_in_last24h', index=8,
      number=9, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='votes_out_yes_last24h', full_name='badoo.meetmaker.response_user_counters_get.votes_out_yes_last24h', index=9,
      number=10, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='votes_out_maybe_last24h', full_name='badoo.meetmaker.response_user_counters_get.votes_out_maybe_last24h', index=10,
      number=11, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_SHOW_NEXT = descriptor.Descriptor(
  name='request_show_next',
  full_name='badoo.meetmaker.request_show_next',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_show_next.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='badoo.meetmaker.request_show_next.offset', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='limit', full_name='badoo.meetmaker.request_show_next.limit', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_gender', full_name='badoo.meetmaker.request_show_next.looking_gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_age_from', full_name='badoo.meetmaker.request_show_next.looking_age_from', index=4,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_age_to', full_name='badoo.meetmaker.request_show_next.looking_age_to', index=5,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='looking_around', full_name='badoo.meetmaker.request_show_next.looking_around', index=6,
      number=7, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_SHOW_NEXT_FACE_TYPE = descriptor.Descriptor(
  name='face_type',
  full_name='badoo.meetmaker.response_show_next.face_type',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.response_show_next.face_type.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo', full_name='badoo.meetmaker.response_show_next.face_type.photo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_paid', full_name='badoo.meetmaker.response_show_next.face_type.is_paid', index=2,
      number=3, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='his_vote', full_name='badoo.meetmaker.response_show_next.face_type.his_vote', index=3,
      number=4, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_RESPONSE_SHOW_NEXT = descriptor.Descriptor(
  name='response_show_next',
  full_name='badoo.meetmaker.response_show_next',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='face', full_name='badoo.meetmaker.response_show_next.face', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_VOTE_INFO_VOTE = descriptor.Descriptor(
  name='vote',
  full_name='badoo.meetmaker.response_vote_info.vote',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='vote', full_name='badoo.meetmaker.response_vote_info.vote.vote', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_new', full_name='badoo.meetmaker.response_vote_info.vote.is_new', index=1,
      number=2, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo_id', full_name='badoo.meetmaker.response_vote_info.vote.photo_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_RESPONSE_VOTE_INFO = descriptor.Descriptor(
  name='response_vote_info',
  full_name='badoo.meetmaker.response_vote_info',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='my_vote', full_name='badoo.meetmaker.response_vote_info.my_vote', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='his_vote', full_name='badoo.meetmaker.response_vote_info.his_vote', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='his_photos', full_name='badoo.meetmaker.response_vote_info.his_photos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_SHOW_MOVE_TO_BEGINNING = descriptor.Descriptor(
  name='request_show_move_to_beginning',
  full_name='badoo.meetmaker.request_show_move_to_beginning',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_show_move_to_beginning.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_to_move', full_name='badoo.meetmaker.request_show_move_to_beginning.user_to_move', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_VOTE_INFO = descriptor.Descriptor(
  name='request_vote_info',
  full_name='badoo.meetmaker.request_vote_info',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='from_user_id', full_name='badoo.meetmaker.request_vote_info.from_user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to_user_id', full_name='badoo.meetmaker.request_vote_info.to_user_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='return_photo', full_name='badoo.meetmaker.request_vote_info.return_photo', index=2,
      number=3, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_FILTER_GET_MAX = descriptor.Descriptor(
  name='request_user_filter_get_max',
  full_name='badoo.meetmaker.request_user_filter_get_max',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_filter_get_max.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_USER_FILTER_GET_MAX = descriptor.Descriptor(
  name='response_user_filter_get_max',
  full_name='badoo.meetmaker.response_user_filter_get_max',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='gender', full_name='badoo.meetmaker.response_user_filter_get_max.gender', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='age_from', full_name='badoo.meetmaker.response_user_filter_get_max.age_from', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='age_to', full_name='badoo.meetmaker.response_user_filter_get_max.age_to', index=2,
      number=3, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_SHOW_CLEAN = descriptor.Descriptor(
  name='request_show_clean',
  full_name='badoo.meetmaker.request_show_clean',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_show_clean.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_LOCK = descriptor.Descriptor(
  name='request_user_lock',
  full_name='badoo.meetmaker.request_user_lock',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_lock.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lock', full_name='badoo.meetmaker.request_user_lock.lock', index=1,
      number=2, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_SERVICE_STATS_GENERAL = descriptor.Descriptor(
  name='request_service_stats_general',
  full_name='badoo.meetmaker.request_service_stats_general',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_SERVICE_STATS_GENERAL = descriptor.Descriptor(
  name='response_service_stats_general',
  full_name='badoo.meetmaker.response_service_stats_general',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='users', full_name='badoo.meetmaker.response_service_stats_general.users', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='romances', full_name='badoo.meetmaker.response_service_stats_general.romances', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_SERVICE_STATS_MEM_USAGE = descriptor.Descriptor(
  name='request_service_stats_mem_usage',
  full_name='badoo.meetmaker.request_service_stats_mem_usage',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_SERVICE_STATS_MEM_USAGE = descriptor.Descriptor(
  name='response_service_stats_mem_usage',
  full_name='badoo.meetmaker.response_service_stats_mem_usage',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_slabs', full_name='badoo.meetmaker.response_service_stats_mem_usage.user_slabs', index=0,
      number=1, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo_slabs', full_name='badoo.meetmaker.response_service_stats_mem_usage.photo_slabs', index=1,
      number=2, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='romances', full_name='badoo.meetmaker.response_service_stats_mem_usage.romances', index=2,
      number=3, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='romances_index', full_name='badoo.meetmaker.response_service_stats_mem_usage.romances_index', index=3,
      number=4, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='romances_user_index', full_name='badoo.meetmaker.response_service_stats_mem_usage.romances_user_index', index=4,
      number=5, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='geo', full_name='badoo.meetmaker.response_service_stats_mem_usage.geo', index=5,
      number=6, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='geo_demo', full_name='badoo.meetmaker.response_service_stats_mem_usage.geo_demo', index=6,
      number=7, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inactivity_passive', full_name='badoo.meetmaker.response_service_stats_mem_usage.inactivity_passive', index=7,
      number=8, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inactivity_shows', full_name='badoo.meetmaker.response_service_stats_mem_usage.inactivity_shows', index=8,
      number=9, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_SERVICE_STATS_DEMO = descriptor.Descriptor(
  name='request_service_stats_demo',
  full_name='badoo.meetmaker.request_service_stats_demo',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M_BY_GENDER_M_BY_AGE_GROUP_M = descriptor.Descriptor(
  name='by_age_group_m',
  full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.by_gender_m.by_age_group_m',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='age_from', full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.by_gender_m.by_age_group_m.age_from', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='age_to', full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.by_gender_m.by_age_group_m.age_to', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.by_gender_m.by_age_group_m.count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M_BY_GENDER_M = descriptor.Descriptor(
  name='by_gender_m',
  full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.by_gender_m',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='gender', full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.by_gender_m.gender', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='by_age_group', full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.by_gender_m.by_age_group', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M = descriptor.Descriptor(
  name='by_demo_m',
  full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='demo', full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.demo', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='by_gender', full_name='badoo.meetmaker.response_service_stats_demo.by_demo_m.by_gender', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_RESPONSE_SERVICE_STATS_DEMO = descriptor.Descriptor(
  name='response_service_stats_demo',
  full_name='badoo.meetmaker.response_service_stats_demo',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='by_demo', full_name='badoo.meetmaker.response_service_stats_demo.by_demo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_SERVICE_STATS_VOTES = descriptor.Descriptor(
  name='request_service_stats_votes',
  full_name='badoo.meetmaker.request_service_stats_votes',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_SERVICE_STATS_VOTES_BY_HOUR_M = descriptor.Descriptor(
  name='by_hour_m',
  full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ts', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.ts', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count_yes', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_yes', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
    descriptor.FieldDescriptor(
      name='count_maybe', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_maybe', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
    descriptor.FieldDescriptor(
      name='count_match', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_match', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
    descriptor.FieldDescriptor(
      name='count_male_yes', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_male_yes', index=4,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count_male_maybe', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_male_maybe', index=5,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count_male_match', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_male_match', index=6,
      number=7, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count_female_yes', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_female_yes', index=7,
      number=8, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count_female_maybe', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_female_maybe', index=8,
      number=9, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count_female_match', full_name='badoo.meetmaker.response_service_stats_votes.by_hour_m.count_female_match', index=9,
      number=10, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_RESPONSE_SERVICE_STATS_VOTES = descriptor.Descriptor(
  name='response_service_stats_votes',
  full_name='badoo.meetmaker.response_service_stats_votes',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='by_hour', full_name='badoo.meetmaker.response_service_stats_votes.by_hour', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_SERVICE_STATS_SHOWS = descriptor.Descriptor(
  name='request_service_stats_shows',
  full_name='badoo.meetmaker.request_service_stats_shows',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RESPONSE_SERVICE_STATS_SHOWS_BY_HOUR_M = descriptor.Descriptor(
  name='by_hour_m',
  full_name='badoo.meetmaker.response_service_stats_shows.by_hour_m',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ts', full_name='badoo.meetmaker.response_service_stats_shows.by_hour_m.ts', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count_no_shows_left', full_name='badoo.meetmaker.response_service_stats_shows.by_hour_m.count_no_shows_left', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_RESPONSE_SERVICE_STATS_SHOWS = descriptor.Descriptor(
  name='response_service_stats_shows',
  full_name='badoo.meetmaker.response_service_stats_shows',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='by_hour', full_name='badoo.meetmaker.response_service_stats_shows.by_hour', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_SUSPEND = descriptor.Descriptor(
  name='request_user_suspend',
  full_name='badoo.meetmaker.request_user_suspend',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_suspend.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suspend', full_name='badoo.meetmaker.request_user_suspend.suspend', index=1,
      number=2, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_HIDE_CONTACT = descriptor.Descriptor(
  name='request_user_hide_contact',
  full_name='badoo.meetmaker.request_user_hide_contact',
  filename='meetmaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='badoo.meetmaker.request_user_hide_contact.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='peer_user_id', full_name='badoo.meetmaker.request_user_hide_contact.peer_user_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hide', full_name='badoo.meetmaker.request_user_hide_contact.hide', index=2,
      number=3, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REQUEST_USER_ADD.fields_by_name['gender'].enum_type = _USER_GENDER
_REQUEST_USER_ADD.fields_by_name['looking_gender'].enum_type = _USER_GENDER
_REQUEST_USER_ADD.fields_by_name['looking_around'].enum_type = _AROUND_TYPE
_REQUEST_USER_ADD.fields_by_name['photo'].message_type = _USER_PHOTO
_REQUEST_USER_UPDATE.fields_by_name['gender'].enum_type = _USER_GENDER
_RESPONSE_USER_GET.fields_by_name['gender'].enum_type = _USER_GENDER
_RESPONSE_USER_GET.fields_by_name['looking_gender'].enum_type = _USER_GENDER
_RESPONSE_USER_GET.fields_by_name['looking_around'].enum_type = _AROUND_TYPE
_REQUEST_PHOTO_ADD.fields_by_name['photo'].message_type = _USER_PHOTO
_REQUEST_PHOTO_UPDATE.fields_by_name['photo'].message_type = _USER_PHOTO
_REQUEST_DEMO_ADD.fields_by_name['priority'].enum_type = _DEMO_PRIORITY
_REQUEST_VOTE_ADD.fields_by_name['vote'].enum_type = _VOTE_TYPE
_RESPONSE_VOTE_ADD.fields_by_name['his_vote'].enum_type = _VOTE_TYPE
_REQUEST_USER_FILTER_SET.fields_by_name['looking_gender'].enum_type = _USER_GENDER
_REQUEST_USER_FILTER_SET.fields_by_name['looking_around'].enum_type = _AROUND_TYPE
_REQUEST_FOLDER_LIST.fields_by_name['folder'].enum_type = _FOLDER_TYPE
_RESPONSE_FOLDER_LIST_USER_DATA.fields_by_name['my_vote'].enum_type = _VOTE_TYPE
_RESPONSE_FOLDER_LIST_USER_DATA.fields_by_name['his_vote'].enum_type = _VOTE_TYPE
_RESPONSE_FOLDER_LIST.fields_by_name['data'].message_type = _RESPONSE_FOLDER_LIST_USER_DATA
_REQUEST_SHOW_NEXT.fields_by_name['looking_gender'].enum_type = _USER_GENDER
_REQUEST_SHOW_NEXT.fields_by_name['looking_around'].enum_type = _AROUND_TYPE
_RESPONSE_SHOW_NEXT_FACE_TYPE.fields_by_name['photo'].message_type = _USER_PHOTO
_RESPONSE_SHOW_NEXT_FACE_TYPE.fields_by_name['his_vote'].enum_type = _VOTE_TYPE
_RESPONSE_SHOW_NEXT.fields_by_name['face'].message_type = _RESPONSE_SHOW_NEXT_FACE_TYPE
_RESPONSE_VOTE_INFO_VOTE.fields_by_name['vote'].enum_type = _VOTE_TYPE
_RESPONSE_VOTE_INFO.fields_by_name['my_vote'].message_type = _RESPONSE_VOTE_INFO_VOTE
_RESPONSE_VOTE_INFO.fields_by_name['his_vote'].message_type = _RESPONSE_VOTE_INFO_VOTE
_RESPONSE_VOTE_INFO.fields_by_name['his_photos'].message_type = _USER_PHOTO
_RESPONSE_USER_FILTER_GET_MAX.fields_by_name['gender'].enum_type = _USER_GENDER
_RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M_BY_GENDER_M.fields_by_name['gender'].enum_type = _USER_GENDER
_RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M_BY_GENDER_M.fields_by_name['by_age_group'].message_type = _RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M_BY_GENDER_M_BY_AGE_GROUP_M
_RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M.fields_by_name['demo'].enum_type = _DEMO_PRIORITY
_RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M.fields_by_name['by_gender'].message_type = _RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M_BY_GENDER_M
_RESPONSE_SERVICE_STATS_DEMO.fields_by_name['by_demo'].message_type = _RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M
_RESPONSE_SERVICE_STATS_VOTES.fields_by_name['by_hour'].message_type = _RESPONSE_SERVICE_STATS_VOTES_BY_HOUR_M
_RESPONSE_SERVICE_STATS_SHOWS.fields_by_name['by_hour'].message_type = _RESPONSE_SERVICE_STATS_SHOWS_BY_HOUR_M

class response_generic(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE_GENERIC

class user_photo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USER_PHOTO

class request_user_add(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_ADD

class request_user_update(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_UPDATE

class request_user_delete(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_DELETE

class request_user_get(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_GET

class response_user_get(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE_USER_GET

class request_photo_add(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_PHOTO_ADD

class request_photo_update(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_PHOTO_UPDATE

class request_photo_delete(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_PHOTO_DELETE

class request_demo_add(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_DEMO_ADD

class request_vote_add(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_VOTE_ADD

class response_vote_add(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE_VOTE_ADD

class request_user_filter_set(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_FILTER_SET

class request_user_mark_as_old(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_MARK_AS_OLD

class request_folder_list(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_FOLDER_LIST

class response_folder_list(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class user_data(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RESPONSE_FOLDER_LIST_USER_DATA
  DESCRIPTOR = _RESPONSE_FOLDER_LIST

class request_user_counters_get(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_COUNTERS_GET

class response_user_counters_get(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE_USER_COUNTERS_GET

class request_show_next(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_SHOW_NEXT

class response_show_next(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class face_type(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RESPONSE_SHOW_NEXT_FACE_TYPE
  DESCRIPTOR = _RESPONSE_SHOW_NEXT

class response_vote_info(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class vote(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RESPONSE_VOTE_INFO_VOTE
  DESCRIPTOR = _RESPONSE_VOTE_INFO

class request_show_move_to_beginning(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_SHOW_MOVE_TO_BEGINNING

class request_vote_info(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_VOTE_INFO

class request_user_filter_get_max(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_FILTER_GET_MAX

class response_user_filter_get_max(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE_USER_FILTER_GET_MAX

class request_show_clean(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_SHOW_CLEAN

class request_user_lock(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_LOCK

class request_service_stats_general(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_SERVICE_STATS_GENERAL

class response_service_stats_general(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE_SERVICE_STATS_GENERAL

class request_service_stats_mem_usage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_SERVICE_STATS_MEM_USAGE

class response_service_stats_mem_usage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE_SERVICE_STATS_MEM_USAGE

class request_service_stats_demo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_SERVICE_STATS_DEMO

class response_service_stats_demo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class by_demo_m(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class by_gender_m(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      
      class by_age_group_m(message.Message):
        __metaclass__ = reflection.GeneratedProtocolMessageType
        DESCRIPTOR = _RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M_BY_GENDER_M_BY_AGE_GROUP_M
      DESCRIPTOR = _RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M_BY_GENDER_M
    DESCRIPTOR = _RESPONSE_SERVICE_STATS_DEMO_BY_DEMO_M
  DESCRIPTOR = _RESPONSE_SERVICE_STATS_DEMO

class request_service_stats_votes(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_SERVICE_STATS_VOTES

class response_service_stats_votes(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class by_hour_m(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RESPONSE_SERVICE_STATS_VOTES_BY_HOUR_M
  DESCRIPTOR = _RESPONSE_SERVICE_STATS_VOTES

class request_service_stats_shows(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_SERVICE_STATS_SHOWS

class response_service_stats_shows(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class by_hour_m(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RESPONSE_SERVICE_STATS_SHOWS_BY_HOUR_M
  DESCRIPTOR = _RESPONSE_SERVICE_STATS_SHOWS

class request_user_suspend(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_SUSPEND

class request_user_hide_contact(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_USER_HIDE_CONTACT

